---
nginx-ingress:
  controller:
    appprotect:
      enable: true
    appprotectdos:
      enable: true
    enableSnippets: true
    image:
      repository: ghcr.io/mhermsdorferf5/nginx-plus-ingress
      tag: 2.4.1-SNAPSHOT-413c0bb
    nginxplus: true
    nginxStatus:
      allowCidrs: 0.0.0.0/0
      port: 9000
    serviceAccount:
      imagePullSecretName: ghcr
  prometheus:
    create: true
