---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: f5-cis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: charts/f5-cis
    repoURL: https://github.com/mhermsdorferf5/modern_app_jumpstart_workshop_infra.git
    targetRevision: HEAD
  destination:
    namespace: f5-cis
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true